[package]
name = "lib-bcml"
version = "0.0.1"
edition = "2018"

[lib]
name = "lib_bcml"
crate-type = ["cdylib"]

[dependencies]
indexmap = { version = "1.3.1", features = ["serde-1"] }
lexical = "5.0.0"
regex = { version = "1.3.3", features = ["perf-literal", "perf-dfa", "perf-inline", "perf-cache"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
serde_yaml = "0.8.11"
yaml-rust = "0.4.3"

[dependencies.pyo3]
version = "0.8.5"
features = ["extension-module"]