name: Build

on:
  workflow_dispatch:

  repository_dispatch:
    types: [trigger-build]

jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: Get Release
          uses: oprypin/find-latest-tag@v1
          with:
            repository: NiceneNerd/BCML
            releases-only: true
          id: tag
        - name: Download Embedded Python
          run: (New-Object Net.WebClient).DownloadFile("https://www.python.org/ftp/python/3.7.9/python-3.7.9-embed-amd64.zip", "$env:temp\python.zip")
        - name: Extract Python
          run: |
            Expand-Archive -Path "$env:temp\python.zip" -DestinationPath "$env:temp\python"
            Set-Content -Path "$env:temp\python\python37._pth" -Value "python37.zip`n.`n.\Lib`n.\Lib\site-packages`n.\DLLs`n"
        - name: Setup pip
          run: |
            (New-Object Net.WebClient).DownloadFile("https://bootstrap.pypa.io/get-pip.py", "$env:temp\get-pip.py")
            & $env:temp\python\python.exe $env:temp\get-pip.py --disable-pip-version-check --no-warn-script-location
        - name: Install BCML
          run: "& \"$env:temp\\python\\python.exe\" -m pip install bcml --upgrade --disable-pip-version-check --no-warn-script-location"
        - name: Get Latest Installer Version
          uses: oprypin/find-latest-tag@v1
          with:
            repository: NiceneNerd/bcml-installer
            releases-only: true
          id: inst
        - name: Add Installer
          run: |
            (New-Object Net.WebClient).DownloadFile("https://github.com/NiceneNerd/bcml-installer/releases/download/${{ steps.inst.outputs.tag }}/setup.exe", "$env:temp\python\setup.exe")
        - name: Create Archive
          run: Compress-Archive -Path "$env:temp\python\*" -DestinationPath ".\bcml-win64-bundle.zip"
        - name: Upload Archive
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: bcml-win64-bundle.zip
            asset_name: bcml-win64-bundle.zip
            tag: ${{ steps.tag.outputs.tag }}
            overwrite: true
