name: Upload Python Package

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.7.6"
            - name: Set up Node.js
              uses: actions/setup-node@v1
              env:
                  RUNNER_TEMP: /tmp
              with:
                  node-version: "14.x"
            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install setuptools wheel twine pynsist
                  sudo apt install nsis
            - name: Generate webpack bundle
              working-directory: ./bcml/assets
              run: |
                  npm install
                  npm build
            - name: Build and publish to PyPI
              env:
                  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: |
                  python setup.py sdist bdist_wheel
                  rm bcml/helpers/7z.so
                  pynsist installer.cfg
                  twine upload dist/*
            - name: Upload installer binary
              uses: skx/github-action-publish-binaries@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  args: "build/nsis/*.exe"
